### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'demonstrations/CarlaNavigation/rule.pt'

### ISSUE THREAD

**Issue by cyrusliu1984** [Usaywook/gin#1]
hello, i am sorry to disturb you ,but i found a issues about your project .
    when i run " bash train.sh " , this  error appear "FileNotFoundError: [Errno 2] No such file or directory: 'demonstrations/CarlaNavigation/rule.pt'" , i can't found this data path file in your porject and also can't found any code to generate this file .
      could you tell me how to get it

**Comment by Usaywook** [comment]
hello @cyrusliu1984,  we uploaded the code so you can generate a demonstration.
After setting RootPATH, you can get demonstration files by executing script demo.sh

**Comment by cyrusliu1984** [comment]
but i can't found  file 'demo.py'  and "autopilot.py" in demo.sh

**Comment by Usaywook** [comment]
We uploaded demo.py and autopilot.py files in response to your request @cyrusliu1984. 
For generating training data, use the "demo.py" file. 
For generating test data, use the "autopilot.py" file.

**Comment by cyrusliu1984** [comment]
oh ~ thank you, i will try later, have a nice day ya

**Comment by Usaywook** [comment]
This is solved
