### ISSUE TITLE
 how to get the graph feature

### ISSUE THREAD

**Issue by raozhongyu** [Usaywook/gin#2]
I'd like to konw how to get the graph feature. I don't find it.

**Comment by Usaywook** [comment]
Hi, you can find how to get graph feature in [this link](https://github.com/Usaywook/gin/blob/86cf573a0f6c54a4de428f40e93774c3d01d9dbb/custom_tasks/envs/carla_navigation.py#L1381)

**Comment by Usaywook** [comment]
This issue is solved.
